# Generated by Django 5.1.4 on 2024-12-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_deck'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maker',
            old_name='desks',
            new_name='decks',
        ),
        migrations.AlterField(
            model_name='deck',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='widgets',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
