# Generated by Django 5.1.4 on 2024-12-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_desks_maker_decks_alter_deck_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
