# Generated by Django 5.1.4 on 2024-12-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_deck_shortcuts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='shortcuts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
